"""add table turist spot

Revision ID: 11e2f21bfa71
Revises: 5f1216b2b4d0
Create Date: 2020-07-21 21:57:57.614365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e2f21bfa71'
down_revision = '5f1216b2b4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourist_spot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id']),
    sa.PrimaryKeyConstraint('id', name='turist_spot_pkey')
    )
    op.create_index('ix_tourist_spot_id', 'tourist_spot', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tourist_spot_id', table_name='tourist_spot')
    op.drop_table('tourist_spot')
    # ### end Alembic commands ###
