"""add table favorite tourist spot

Revision ID: 6bd2930aa71f
Revises: 11e2f21bfa71
Create Date: 2020-07-22 10:05:52.795325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd2930aa71f'
down_revision = '11e2f21bfa71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_tourist_spot',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tourist_spot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_user_id_fkey'),
    sa.ForeignKeyConstraint(['tourist_spot_id'], ['tourist_spot.id'], name='favorite_spot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_turist_spot_pkey')
    )
    op.create_index('ix_favorite_tourist_spot_id', 'favorite_tourist_spot', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorite_tourist_spot_id', table_name='favorite_tourist_spot')
    op.drop_table('favorite_tourist_spot')
    # ### end Alembic commands ###
